Models/ErrorViewModel.cs
namespace TE_CODEFIRST.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Trainee.cs
using System.ComponentModel.DataAnnotations;

namespace TE_CODEFIRST.Models
{
    public class Trainee
    {
        [Key]
        public int TraineeID { get; set; }

        [Required(ErrorMessage = "Enter Name")]
        [RegularExpression(@"^([A-Za-z]+)$")]
        public string TraineeName { get; set; }

        [Range(21, 58, ErrorMessage = "Enter age between 21 to 58")]
        public int TraineeAge { get; set; }

        public DateTime TraineeDOJ { get; set; }
        public DateTime TraineeDOB { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string TraineeMobile { get; set; }

        [DataType(DataType.EmailAddress)]
        public string TraineeEmail { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Enter the Password")]
        public string TraineePassword { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Enter the Confirm Password")]
        [Compare("TraineePassword", ErrorMessage = "Password does not match")]
        public string TraineeConfirmPassword { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TE_CODEFIRST.Models;

namespace TE_CODEFIRST.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using TE_CODEFIRST.Data;
using TE_CODEFIRST.Models;
//EncryptDecrypt
using TE_CODEFIRST.Utilities;

namespace TE_CODEFIRST.Controllers
{
    public class TraineesController : Controller
    {
        private readonly ILogger<TraineesController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly TraineeDbContext _context;
        public TraineesController(ILogger<TraineesController> logger, IToastNotification toastNotification, TraineeDbContext context)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _context = context;
        }

        // GET: Trainees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Trainees.ToListAsync());
        }

        // GET: Trainees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trainees == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .FirstOrDefaultAsync(m => m.TraineeID == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // GET: Trainees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trainees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TraineeID,TraineeName,TraineeAge,TraineeDOJ,TraineeDOB,TraineeMobile,TraineeEmail,TraineePassword,TraineeConfirmPassword")] Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                //classname.methodname(123456)
                //EncryptDecrypt.Encrypt(trainee.TraineePassword);
                //trainee.TraineePassword=V0P1bOxKJEudFjsUjN35Cw==
                trainee.TraineePassword = EncryptDecrypt.Encrypt(trainee.TraineePassword);
                _context.Add(trainee);
                await _context.SaveChangesAsync();
                _toastNotification.AddSuccessToastMessage("Employee created successfully");
                return RedirectToAction(nameof(Index));
            }
            return View(trainee);
        }

        // GET: Trainees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trainees == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees.FindAsync(id);
            if (trainee == null)
            {
                return NotFound();
            }
            return View(trainee);
        }

        // POST: Trainees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TraineeID,TraineeName,TraineeAge,TraineeDOJ,TraineeDOB,TraineeMobile,TraineeEmail,TraineePassword,TraineeConfirmPassword")] Trainee trainee)
        {
            if (id != trainee.TraineeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    trainee.TraineePassword = EncryptDecrypt.Encrypt(trainee.TraineePassword);
                    _context.Update(trainee);
                    await _context.SaveChangesAsync();
                    _toastNotification.AddWarningToastMessage("Employee updated successfully");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TraineeExists(trainee.TraineeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainee);
        }

        // GET: Trainees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trainees == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .FirstOrDefaultAsync(m => m.TraineeID == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // POST: Trainees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trainees == null)
            {
                return Problem("Entity set 'TraineeDbContext.Trainees'  is null.");
            }
            var trainee = await _context.Trainees.FindAsync(id);
            if (trainee != null)
            {
                _context.Trainees.Remove(trainee);
            }

            await _context.SaveChangesAsync();
            _toastNotification.AddErrorToastMessage("Employee deleted successfully");
            return RedirectToAction(nameof(Index));
        }

        private bool TraineeExists(int id)
        {
            return _context.Trainees.Any(e => e.TraineeID == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TE_CODEFIRST</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TE_CODEFIRST.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TE_CODEFIRST</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainees" asp-action="Index">Trainees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TE_CODEFIRST - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

Views/Trainees/Create.cshtml
@model TE_CODEFIRST.Models.Trainee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Trainee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TraineeName" class="control-label"></label>
                <input asp-for="TraineeName" class="form-control" />
                <span asp-validation-for="TraineeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeAge" class="control-label"></label>
                <input asp-for="TraineeAge" class="form-control" />
                <span asp-validation-for="TraineeAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeDOJ" class="control-label"></label>
                <input asp-for="TraineeDOJ" class="form-control" />
                <span asp-validation-for="TraineeDOJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeDOB" class="control-label"></label>
                <input asp-for="TraineeDOB" class="form-control" />
                <span asp-validation-for="TraineeDOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeMobile" class="control-label"></label>
                <input asp-for="TraineeMobile" class="form-control" />
                <span asp-validation-for="TraineeMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeEmail" class="control-label"></label>
                <input asp-for="TraineeEmail" class="form-control" />
                <span asp-validation-for="TraineeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineePassword" class="control-label"></label>
                <input asp-for="TraineePassword" class="form-control" />
                <span asp-validation-for="TraineePassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeConfirmPassword" class="control-label"></label>
                <input asp-for="TraineeConfirmPassword" class="form-control" />
                <span asp-validation-for="TraineeConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trainees/Delete.cshtml
@model TE_CODEFIRST.Models.Trainee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeAge)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeAge)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeDOJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeDOJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeDOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeDOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeMobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeMobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineePassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineePassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeConfirmPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeConfirmPassword)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TraineeID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Trainees/Details.cshtml
@model TE_CODEFIRST.Models.Trainee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Trainee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeAge)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeAge)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeDOJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeDOJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeDOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeDOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeMobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeMobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineePassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineePassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TraineeConfirmPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TraineeConfirmPassword)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TraineeID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Trainees/Edit.cshtml
@model TE_CODEFIRST.Models.Trainee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Trainee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TraineeID" />
            <div class="form-group">
                <label asp-for="TraineeName" class="control-label"></label>
                <input asp-for="TraineeName" class="form-control" />
                <span asp-validation-for="TraineeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeAge" class="control-label"></label>
                <input asp-for="TraineeAge" class="form-control" />
                <span asp-validation-for="TraineeAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeDOJ" class="control-label"></label>
                <input asp-for="TraineeDOJ" class="form-control" />
                <span asp-validation-for="TraineeDOJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeDOB" class="control-label"></label>
                <input asp-for="TraineeDOB" class="form-control" />
                <span asp-validation-for="TraineeDOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeMobile" class="control-label"></label>
                <input asp-for="TraineeMobile" class="form-control" />
                <span asp-validation-for="TraineeMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeEmail" class="control-label"></label>
                <input asp-for="TraineeEmail" class="form-control" />
                <span asp-validation-for="TraineeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineePassword" class="control-label"></label>
                <input asp-for="TraineePassword" class="form-control" />
                <span asp-validation-for="TraineePassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeConfirmPassword" class="control-label"></label>
                <input asp-for="TraineeConfirmPassword" class="form-control" />
                <span asp-validation-for="TraineeConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trainees/Index.cshtml
@model IEnumerable<TE_CODEFIRST.Models.Trainee>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">
        <p> <a asp-action="Create" class="text-success"><i class="fa-solid fa-plus"></i></a>
        </p>
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TraineeName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.TraineeAge)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.TraineeDOJ)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.TraineeDOB)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.TraineeMobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TraineeEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TraineePassword)
            </th>
            @* <th>
            @Html.DisplayNameFor(model => model.TraineeConfirmPassword)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TraineeName)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.TraineeAge)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.TraineeDOJ)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.TraineeDOB)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.TraineeMobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TraineeEmail)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TraineePassword)
                </td>
              @*<td>
            @Html.DisplayFor(modelItem => item.TraineeConfirmPassword)
            </td>
            *@
            <td>
                    <a asp-action="Edit" asp-route-id="@item.TraineeID" class="text-warning"><i class="fa-solid fa-pen-to-square"></i></a> |
                    <a asp-action="Details" asp-route-id="@item.TraineeID" class="text-info"><i class="fa-sharp fa-solid fa-circle-info"></i></a> |
                    <a asp-action="Delete" asp-route-id="@item.TraineeID" class="text-danger"><i class="fa-solid fa-trash"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>